wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711604521.503418
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.8.18
      5: 0.15.8
      8:
      - 5
