wandb_version: 1

gamma:
  desc: null
  value: 0.95
lr:
  desc: null
  value: 0.001
eps:
  desc: null
  value: 1
eps_decay:
  desc: null
  value: 0.9999
eps_min:
  desc: null
  value: 0.01
max_update_steps:
  desc: null
  value: 100
total_ep:
  desc: null
  value: 5000
book_decay:
  desc: null
  value: 0.1
book_term:
  desc: null
  value: 4
ep_save:
  desc: null
  value: 100
buffer_size:
  desc: null
  value: 10000
trainstart_buffersize:
  desc: null
  value: 5000
avg_dist_deque_len:
  desc: null
  value: 300
plot_term:
  desc: null
  value: 30
replay_times:
  desc: null
  value: 32
target_update:
  desc: null
  value: 10
map_size:
  desc: null
  value: 14
predator1_view_range:
  desc: null
  value: 6
predator2_view_range:
  desc: null
  value: 3
n_predator1:
  desc: null
  value: 3
n_predator2:
  desc: null
  value: 3
n_prey:
  desc: null
  value: 12
tag_reward:
  desc: null
  value: 3
tag_penalty:
  desc: null
  value: -0.2
move_penalty:
  desc: null
  value: -0.15
seed:
  desc: null
  value: 874
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711636473.911449
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.18
      5: 0.15.8
      8:
      - 4
      - 5
