wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711604092.158647
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.8.18
      5: 0.15.8
      8:
      - 4
      - 5
    visualize:
      label_distribution:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: label
            value: count
          stringSettings:
            title: Label Distribution
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: label_distribution_table
                fields: []
